### ISSUE TITLE
Made a little change in your code

### ISSUE THREAD

**Issue by faganzert** [lhguerra/react-native-spinning-button#1]
Hi, thanks for wrapping it all up! It works like a charm!

In order to work well according to my needs, I had to perform a little change in your code, as follows:

I changed from:

	_onPressButton = () => {
		if (this.state.rotateValue._value == 0 || (this.state.rotateValue._value % 360) == 0) 
		{
			Animated.spring(
				this.state.rotateValue,
				{
					toValue: this.state.rotateValue._value + 360,
				}
			).start()
		}
		
	     this.props.onPress()
	}

to:

	_onPressButton = () => {
		if (this.state.rotateValue._value == 0 || (this.state.rotateValue._value % 360) == 0) 
		{
			Animated.spring(
				this.state.rotateValue,
				{
					toValue: this.state.rotateValue._value + 360,
				}
			).start()
		}
		
		setTimeout(()=>{
			this.props.onPress()
		},250);
	}

-> Please note that the little delay caused by the setTimeout function, which lets the button spinning finish properly before calling the callback. This solved my problem for good.

All in all, thanks for your contribution.

Cheers! =)

**Comment by lhguerra** [comment]
Hello, @FabricioGanzert !

Thank you too for your contribution, I'll look into the issue and come back to you with news about it ;)

**Comment by faganzert** [comment]
Hi there =)
See, the reason I put a simple setTimeout there is mainly because "Animated.spring" thing acts like an Async function ( is it?), not giving enough time to spin properly prior to call the callback function. So I had to calculate the exact time that it takes to complete a perfect 360º before calling the "this.props.onPress()".

Check it out yourself. You are going to see what I'm talking about.

Great job, though. Thanks, all the best.

**Comment by lhguerra** [comment]
Hi, I opened a PR intending to fix this issue. It turns out the Animated.spring API accepts a callback in the start() event, so I just moved the onPress prop call to that argument.

Could you please test if this works in your scenario?

**Comment by faganzert** [comment]
Mate, I did what you suggested. Nice! However, turns out the start(callback) takes too long to finish the whole spin effect... Like, way longer than my 250ms - which I already think its quite a long time to wait for a screen to open up.
Anyway, I'm still sticking to my timeout solution for practical reasons.
Cheers, all the best 
[]'s

**Comment by lhguerra** [comment]
I guess I'll create an issue to add a better api to this component, like adding a prop to alter the animation duration and what effect to use. Thanks again for your feedback!

**Comment by faganzert** [comment]
Well, personally I think its a great job, all wrapped up and everything. I'm using on a personal project 99% of that code as it is. Perhaps the best solution is to leave for the programmer to decide how the timeouts are going to be managed after all.
Keep it up,
[]'s
